apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: HetznerCluster
metadata:
  name: "${CLUSTER_NAME}"
spec:
  hcloudPlacementGroups:
    - name: control-plane
      type: spread
    - name: md-0
      type: spread
