apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: HCloudMachineTemplate
metadata:
  name: "${CLUSTER_NAME}-md-0"
spec:
  template:
    spec:
      type: "${HCLOUD_WORKER_MACHINE_TYPE}"
      imageName: "ubuntu-22.04"
      publicNetwork:
        enableIPv4: false
        enableIPv6: true
