apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: HetznerCluster
metadata:
  name: "${CLUSTER_NAME}"
spec:
  hcloudNetwork:
    enabled: true
  controlPlaneRegions:
    - "${HCLOUD_REGION}"
  controlPlaneEndpoint:
    host: ""
    port: 443
  controlPlaneLoadBalancer:
    region: "${HCLOUD_REGION}"
    useIPv6Endpoint: true
  sshKeys:
    hcloud:
      - name: "${HCLOUD_SSH_KEY}"
  hetznerSecretRef:
    name: hetzner
    key:
      hcloudToken: hcloud
      hetznerRobotPassword: robot-password
      hetznerRobotUser: robot-user
