apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: HetznerBareMetalMachineTemplate
metadata:
  name: "${CLUSTER_NAME}-md-1"
spec:
  template:
    spec:
      installImage:
        image:
          path: /root/.oldroot/nfs/images/Ubuntu-2404-noble-amd64-base.tar.gz
        partitions:
          - fileSystem: esp
            mount: /boot/efi
            size: 512M
          - mount: /boot
            fileSystem: ext4
            size: 1024M
          - mount: /
            fileSystem: ext4
            size: all
        postInstallScript: |
          #!/bin/bash
          mkdir -p /etc/cloud/cloud.cfg.d && touch /etc/cloud/cloud.cfg.d/99-custom-networking.cfg
          echo "network: { config: disabled }" > /etc/cloud/cloud.cfg.d/99-custom-networking.cfg
          apt-get update && apt-get install -y cloud-init apparmor apparmor-utils
          cloud-init clean --logs
      sshSpec:
        portAfterInstallImage: 22
        portAfterCloudInit: 22
        secretRef:
          name: robot-ssh
          key:
            name: sshkey-name
            publicKey: ssh-publickey
            privateKey: ssh-privatekey
