version: "2"
run:
  go: "1.22"
  modules-download-mode: readonly
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - copyloopvar
    - dogsled
    - durationcheck
    - errcheck
    - errchkjson
    - gocritic
    - godot
    - goprintffuncname
    - gosec
    - govet
    - importas
    - ineffassign
    - loggercheck
    - misspell
    - nakedret
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - staticcheck
    - thelper
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    gocritic:
      disabled-checks:
        - appendAssign
        - dupImport
        - evalOrder
        - ifElseChain
        - octalLiteral
        - regexpSimplify
        - sloppyReassign
        - truncateCmp
        - typeDefFirst
        - unnamedResult
        - unnecessaryDefer
        - whyNoLint
        - wrapperFunc
        - rangeValCopy
        - hugeParam
      enabled-tags:
        - diagnostic
        - experimental
        - performance
    godot:
      scope: toplevel
      exclude:
        - ^ \+.*
        - ^ ANCHOR.*
    gosec:
      excludes:
        - G307
        - G108
        - G106
    importas:
      alias:
        - pkg: k8s.io/api/core/v1
          alias: corev1
        - pkg: k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1
          alias: apiextensionsv1
        - pkg: k8s.io/apimachinery/pkg/apis/meta/v1
          alias: metav1
        - pkg: k8s.io/apimachinery/pkg/api/errors
          alias: apierrors
        - pkg: k8s.io/apimachinery/pkg/util/errors
          alias: kerrors
        - pkg: k8s.io/component-base/logs/api/v1
          alias: logsv1
        - pkg: sigs.k8s.io/controller-runtime
          alias: ctrl
        - pkg: k8s.io/apimachinery/pkg/util/runtime
          alias: utilruntime
        - pkg: sigs.k8s.io/cluster-api/api/v1beta1
          alias: clusterv1
        - pkg: sigs.k8s.io/cluster-api/bootstrap/kubeadm/api/v1beta1
          alias: bootstrapv1
        - pkg: sigs.k8s.io/controller-runtime/pkg/metrics/server
          alias: metricsserver
        - pkg: sigs.k8s.io/controller-runtime/pkg/client/fake
          alias: fakeclient
      no-unaliased: true
    nolintlint:
      require-specific: true
      allow-unused: false
  exclusions:
    generated: lax
    rules:
      - linters:
          - revive
        text: 'exported: exported method .*\.(Reconcile|SetupWithManager|SetupWebhookWithManager) should have comment or be unexported'
      - linters:
          - errcheck
        text: Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*print(f|ln)?|os\.(Un)?Setenv). is not checked
      - linters:
          - revive
        text: exported (method|function|type|const) (.+) should have comment or be unexported
        source: (func|type).*Fake.*
      - linters:
          - revive
        path: fake_\.go
        text: exported (method|function|type|const) (.+) should have comment or be unexported
      - linters:
          - revive
        path: (framework|e2e)/.*.go
        text: exported (method|function|type|const) (.+) should have comment or be unexported
      - linters:
          - revive
        path: (e2e|infrastructure/hetzner)/.*.go
        text: exported (method|function|type|const) (.+) should have comment or be unexported
      - linters:
          - unparam
        text: always receives
      - path: _test\.go
        text: should not use dot imports
      - path: (framework|e2e)/.*.go
        text: should not use dot imports
      - path: _test\.go
        text: cyclomatic complexity
      - linters:
          - gocritic
        text: 'appendAssign: append result not assigned to the same slice'
      - linters:
          - staticcheck
        path: .*(api|types)\/.*\/conversion.*\.go$
        text: 'SA1019: in.(.+) is deprecated'
      - linters:
          - staticcheck
        path: pkg/services/baremetal/baremetal/baremetal.go
        text: 'SA1019: .*FailureReason is deprecated'
      - linters:
          - revive
        path: .*(api|types|test)\/.*\/conversion.*\.go$
        text: exported (method|function|type|const) (.+) should have comment or be unexported
      - linters:
          - revive
        path: .*(api|types|test)\/.*\/conversion.*\.go$
        text: 'var-naming: don''t use underscores in Go names;'
      - linters:
          - revive
        path: .*(api|types)\/.*\/conversion.*\.go$
        text: 'receiver-naming: receiver name'
      - linters:
          - staticcheck
        path: .*(api|types|test)\/.*\/conversion.*\.go$
        text: 'ST1003: should not use underscores in Go names;'
      - linters:
          - staticcheck
        path: .*(api|types)\/.*\/conversion.*\.go$
        text: 'ST1016: methods on the same type should have the same receiver name'
      - linters:
          - gocritic
        path: _test\.go
        text: 'deferInLoop: Possible resource leak, ''defer'' is called in the ''for'' loop'
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/syself/cluster-api-provider-hetzner)
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
