# permissions for end users to view hetznerbaremetalhosts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hetznerbaremetalhost-viewer-role
rules:
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - hetznerbaremetalhosts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - hetznerbaremetalhosts/status
  verbs:
  - get
