# permissions for end users to view hetznerbaremetalremediationtemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hetznerbaremetalremediationtemplate-viewer-role
rules:
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - hetznerbaremetalremediationtemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - hetznerbaremetalremediationtemplates/status
  verbs:
  - get
