#!/usr/bin/env bash

# Copyright 2022 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Bash Strict Mode: https://github.com/guettli/bash-strict-mode
trap 'echo "Warning: A command has failed. Exiting the script. Line was ($0:$LINENO): $(sed -n "${LINENO}p" "$0")"; exit 3' ERR
set -Eeuo pipefail

if ! ./hack/tools/bin/setup-envtest list | grep -q "$KUBEBUILDER_ENVTEST_KUBERNETES_VERSION"; then
    echo "./hack/tools/bin/setup-envtest is outdated. It does not support $KUBEBUILDER_ENVTEST_KUBERNETES_VERSION."
    echo "Remove ./hack/tools/bin/setup-envtest and call make again."
    exit 1
fi

KUBEBUILDER_ASSETS=$(./hack/tools/bin/setup-envtest use --use-env \
    --bin-dir "$PWD/hack/tools/bin" -p path \
    "$KUBEBUILDER_ENVTEST_KUBERNETES_VERSION")

if [[ ! -e $KUBEBUILDER_ASSETS ]]; then
    echo "$KUBEBUILDER_ASSETS does not exist. Check our setup."
    echo "Maybe env var wrong: KUBEBUILDER_ASSETS=$KUBEBUILDER_ASSETS"
    echo "Maybe this helps:"
    echo "    rm -rf hack/tools/bin/setup-envtest"
    echo "    make setup-envtest"
    exit 1
fi
export KUBEBUILDER_ASSETS

if [[ ! -e $KUBEBUILDER_ASSETS ]]; then
    echo "error: $KUBEBUILDER_ASSETS does not exit!"
    exit 1
fi

mkdir -p .coverage

mkdir -p tmp

hack/tools/bin/gotestsum \
    --jsonfile=.reports/go-test-output.json \
    --junitfile=.coverage/junit.xml \
    --format testname -- \
    -covermode=atomic -coverprofile=.coverage/cover.out -p=1 -v -timeout 5m \
    ./controllers/... ./pkg/... ./api/... |
    tee tmp/test-unit-unfiltered.log |
    ./hack/filter-caph-controller-manager-logs.py -

# Remove autogenerated files from the coverage profile to keep reports focused on hand-written code.
tmp_cover_profile=$(mktemp)
grep -vP "zz_generated|/client/mocks/" .coverage/cover.out >"$tmp_cover_profile"
mv "$tmp_cover_profile" .coverage/cover.out

echo "Files with worst coverage:"
hack/go-files-with-worst-coverage.py .coverage/cover.out

go run github.com/gametimesf/gocov/gocov@latest convert .coverage/cover.out |
    go run github.com/AlekSi/gocov-xml@latest >.coverage/cover.xml

pipx run pycobertura show --format html --output .coverage/cover.html --source "$PWD" .coverage/cover.xml
