name: "Test Release"
description: "Testing Release"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
    - uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4
      with:
        path: hack/tools/bin
        key: ${{ runner.os }}-tools-bin-release-${{ hashFiles('Makefile') }}
        restore-keys: |
          ${{ runner.os }}-tools-bin-release-
          ${{ runner.os }}-tools-bin-

    - name: Generate metadata
      id: meta
      uses: ./.github/actions/metadata
      with:
        metadata_flavor: ${{ env.metadata_flavor }}
        metadata_tags: ${{ env.metadata_tags }}

    - name: Test Release
      shell: bash
      env:
        TAG: ${{ steps.meta.outputs.version }}
      run: make test-release
    - name: Upload artifact
      uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4
      if: ${{ !cancelled() }}
      with:
        name: test-release
        path: out
