name: "Test Release"
description: "Testing Release"
runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/setup-go
    - uses: actions/cache@940f3d7cf195ba83374c77632d1e2cbb2f24ae68 # v3
      with:
        path: hack/tools/bin
        key: ${{ runner.os }}-tools-bin-release-${{ hashFiles('Makefile') }}
        restore-keys: |
          ${{ runner.os }}-tools-bin-release-
          ${{ runner.os }}-tools-bin-

    - name: Generate metadata
      id: meta
      uses: ./.github/actions/metadata
      with:
        metadata_flavor: ${{ env.metadata_flavor }}
        metadata_tags: ${{ env.metadata_tags }}

    - name: Test Release
      shell: bash
      env:
        TAG: ${{ steps.meta.outputs.version }}
      run: make test-release
    - name: Upload artifact
      uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3
      with:
        name: test-release
        path: out
