// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	hcloudclient "github.com/syself/cluster-api-provider-hetzner/pkg/services/hcloud/client"
)

// Factory is an autogenerated mock type for the Factory type
type Factory struct {
	mock.Mock
}

type Factory_Expecter struct {
	mock *mock.Mock
}

func (_m *Factory) EXPECT() *Factory_Expecter {
	return &Factory_Expecter{mock: &_m.Mock}
}

// NewClient provides a mock function with given fields: hcloudToken
func (_m *Factory) NewClient(hcloudToken string) hcloudclient.Client {
	ret := _m.Called(hcloudToken)

	if len(ret) == 0 {
		panic("no return value specified for NewClient")
	}

	var r0 hcloudclient.Client
	if rf, ok := ret.Get(0).(func(string) hcloudclient.Client); ok {
		r0 = rf(hcloudToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(hcloudclient.Client)
		}
	}

	return r0
}

// Factory_NewClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewClient'
type Factory_NewClient_Call struct {
	*mock.Call
}

// NewClient is a helper method to define mock.On call
//   - hcloudToken string
func (_e *Factory_Expecter) NewClient(hcloudToken interface{}) *Factory_NewClient_Call {
	return &Factory_NewClient_Call{Call: _e.mock.On("NewClient", hcloudToken)}
}

func (_c *Factory_NewClient_Call) Run(run func(hcloudToken string)) *Factory_NewClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Factory_NewClient_Call) Return(_a0 hcloudclient.Client) *Factory_NewClient_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Factory_NewClient_Call) RunAndReturn(run func(string) hcloudclient.Client) *Factory_NewClient_Call {
	_c.Call.Return(run)
	return _c
}

// NewFactory creates a new instance of Factory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *Factory {
	mock := &Factory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
