name: "Manager Image"
description: "Build and Push Manager Image"
inputs:
  registry_password:
    description: "registry_password"
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0

    - name: Login to ghcr.io for CI
      uses: docker/login-action@06fb636fac595d6fb4b28a5dfcb21a6f5091859c # v4.5.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ env.registry_password }}

    - name: Generate metadata
      id: meta
      uses: ./.github/actions/metadata
      with:
        metadata_flavor: ${{ env.metadata_flavor }}
        metadata_tags: ${{ env.metadata_tags }}

    # Load Golang cache build from GitHub
    - name: Load Caph Golang cache build from GitHub
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      id: cache
      with:
        path: /tmp/.cache/caph
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}-caph-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}-caph-
          ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}-
          ${{ runner.os }}-go-

    - name: Create Caph cache directory
      if: ${{ steps.cache.outputs.cache-hit != 'true' }}
      shell: bash
      run: |
        mkdir -p /tmp/.cache/caph

    # Import GitHub's cache build to docker cache
    - name: Copy Caph Golang cache to docker cache
      uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
      with:
        provenance: false
        context: /tmp/.cache/caph
        file: ./images/cache/Dockerfile
        push: false
        platforms: linux/amd64
        target: import-cache

    - name: Build and push manager image
      uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7
      with:
        provenance: false
        context: .
        push: true
        file: ./images/caph/Dockerfile
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64
