resources:
  - namespace.yaml

helmChartInflationGenerator:
  - chartName: promtail
    chartRepoUrl: https://grafana.github.io/helm-charts
    releaseNamespace: observability
    releaseName: promtail
    values: ./hack/observability/promtail/values.yaml
  - chartName: loki
    chartRepoUrl: https://grafana.github.io/helm-charts
    releaseNamespace: observability
    releaseName: loki
    values: ./hack/observability/loki/values.yaml
  - chartName: grafana
    chartRepoUrl: https://grafana.github.io/helm-charts
    releaseNamespace: observability
    releaseName: grafana
    values: ./hack/observability/grafana/values.yaml
