// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	robotclient "github.com/syself/cluster-api-provider-hetzner/pkg/services/baremetal/client/robot"
)

// Factory is an autogenerated mock type for the Factory type
type Factory struct {
	mock.Mock
}

// NewClient provides a mock function with given fields: _a0
func (_m *Factory) NewClient(_a0 robotclient.Credentials) robotclient.Client {
	ret := _m.Called(_a0)

	var r0 robotclient.Client
	if rf, ok := ret.Get(0).(func(robotclient.Credentials) robotclient.Client); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(robotclient.Client)
		}
	}

	return r0
}
