name: E2E Upgrade CAPH
on:
  workflow_dispatch:
env:
  IMAGE_NAME: caph-staging
  REGISTRY: ghcr.io/syself
  metadata_flavor: latest=false
  metadata_tags: type=sha
  registry_password: ${{ secrets.GITHUB_TOKEN }}
jobs:
  manager-image:
    name: Build and push manager image
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      - name: Build and push manager image
        id: manager-image
        uses: ./.github/actions/manager-image

  test-release:
    name: Test Release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      - name: Test Release
        id: manager-image
        uses: ./.github/actions/test-release

  e2e-upgrade-caph:
    name: Test upgrade CAPH
    concurrency: ci-${{ github.ref }}-e2e-upgrade-caph
    runs-on: ubuntu-latest
    permissions:
      # Required for hcloud TPS
      id-token: write
    needs:
      - manager-image
      - test-release
    steps:
      - name: checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      - name: Run e2e Test
        id: e2e
        uses: ./.github/actions/e2e
        with:
          e2e_name: upgrade-caph
          e2e_make_target: test-e2e-upgrade-caph
          e2e_hcloud_token: ${{ secrets.HCLOUD_TOKEN }}
          e2e_robot_user: ${{ secrets.HETZNER_ROBOT_USER }}
          e2e_robot_password: ${{ secrets.HETZNER_ROBOT_PASSWORD }}
          e2e_ssh_pub: ${{ secrets.HETZNER_SSH_PUB }}
          e2e_ssh_priv: ${{ secrets.HETZNER_SSH_PRIV }}
