name: E2E Periodic Tests
on:
  workflow_dispatch:
env:
  IMAGE_NAME: caph-staging
  REGISTRY: ghcr.io/syself
  metadata_flavor: latest=false
  metadata_tags: type=sha
  registry_password: ${{ secrets.GITHUB_TOKEN }}
jobs:
  manager-image:
    name: Build and push manager image
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Build and push manager image
        id: manager-image
        uses: ./.github/actions/manager-image

  test-release:
    name: Test Release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Test Release
        id: manager-image
        uses: ./.github/actions/test-release

  e2e-hcloud-basic:
    name: Test Hcloud Basic
    concurrency: ci-${{ github.ref }}-e2e-basic-periodic
    runs-on: ubuntu-latest
    permissions:
      # Required for hcloud TPS
      id-token: write
    needs:
      - manager-image
      - test-release
    steps:
      - name: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Run e2e Test
        id: e2e
        uses: ./.github/actions/e2e
        with:
          e2e_name: hcloud-basic
          e2e_make_target: test-e2e-hcloud

  e2e-hcloud-feature:
    name: Test Hcloud Features
    concurrency: ci-${{ github.ref }}-e2e-feature
    runs-on: ubuntu-latest
    permissions:
      # Required for hcloud TPS
      id-token: write
    needs:
      - manager-image
      - test-release
    steps:
      - name: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Run e2e Test
        id: e2e
        uses: ./.github/actions/e2e
        with:
          e2e_name: hcloud-feature
          e2e_make_target: test-e2e-feature

  e2e-hcloud-lifecycle:
    name: Test Hcloud Lifecycle
    concurrency: ci-${{ github.ref }}-e2e-lifecycle
    runs-on: ubuntu-latest
    permissions:
      # Required for hcloud TPS
      id-token: write
    needs:
      - manager-image
      - test-release
    steps:
      - name: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Run e2e Test
        id: e2e
        uses: ./.github/actions/e2e
        with:
          e2e_name: hcloud-lifecycle
          e2e_make_target: test-e2e-lifecycle

  e2e-hcloud-conformance:
    name: Test Hcloud Conformance
    concurrency: ci-${{ github.ref }}-e2e-conformance
    runs-on: ubuntu-latest
    permissions:
      # Required for hcloud TPS
      id-token: write
    needs:
      - manager-image
      - test-release
    steps:
      - name: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Run e2e Test
        id: e2e
        uses: ./.github/actions/e2e
        with:
          e2e_name: hcloud-conformance
          e2e_make_target: test-e2e-conformance
