name: E2E Feature
on:
  workflow_dispatch:
env:
  IMAGE_NAME: caph-staging
  REGISTRY: ghcr.io/syself
  metadata_flavor: latest=false
  metadata_tags: type=sha
  registry_password: ${{ secrets.GITHUB_TOKEN }}
jobs:
  manager-image:
    name: Build and push manager image
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Build and push manager image
        id: manager-image
        uses: ./.github/actions/manager-image

  test-release:
    name: Test Release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Test Release
        id: manager-image
        uses: ./.github/actions/test-release

  e2e-hcloud-feature:
    name: Test Hcloud Features
    concurrency: ci-${{ github.ref }}-e2e-feature
    runs-on: ubuntu-latest
    permissions:
      # Required for hcloud TPS
      id-token: write
    needs:
      - manager-image
      - test-release
    steps:
      - name: checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Run e2e Test
        id: e2e
        uses: ./.github/actions/e2e
        with:
          e2e_name: hcloud-feature
          e2e_make_target: test-e2e-feature
