name: yamllint test

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
    branches:
      - main
      - 'releases/**'
    paths:
      - '**.yaml'
      - '**.yml'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install yamllint
        run: pip install yamllint

      - name: Lint YAML files
        run: yamllint -c .github/linters/yaml-lint.yaml . --format github