name: Report Binsize Treemap
# yamllint disable rule:line-length
on: # yamllint disable-line rule:truthy
  workflow_dispatch:
jobs:
  report-binsize-treemap:
    name: Report Binsize Treemap
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: Fixup git permissions
        # https://github.com/actions/checkout/issues/766
        shell: bash
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          go-version-file: "go.mod"

      - name: Create Binsize Report
        run: make caph report-binsize-treemap-all

      - name: Upload Report
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: ${{ !cancelled() }}
        with:
          name: reports-${{ github.sha }}
          path: .reports
          include-hidden-files: true
          retention-days: 90
