name: shellcheck
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
    branches:
      - main
      - 'releases/**'
    paths:
      - '**.sh'
jobs:
  shellcheck:
    name: shellcheck-lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: run shellcheck
        run: make shell-lint